version: "3.8"

x-env: &env
  ENABLE_METRICS_EXPORTER: 1
  METRICS_EXPORTER_PORT: ${METRICS_EXPORTER_PORT}
  REDIS_URL: redis://redis
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/fireagg
  BENCHMARK_TRADES_PER_SECOND_TARGET: 100

x-fireagg: &fireagg
  restart: unless-stopped
  environment:
    <<: *env
  build:
    context: "."
  volumes:
    - ./:/app
  depends_on:
    - redis
    - postgres
  expose:
    # Prometheus metrics
    - ${METRICS_EXPORTER_PORT}
  networks:
    - metrics
    - main

services:
  postgres:
    restart: unless-stopped
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: fireagg
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/committed:/docker-entrypoint-initdb.d
      - pgdata:/home/postgres/pgdata
    networks:
      - main

  redis:
    image: redis:7.2.0
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - main

  db_insertion:
    <<: *fireagg
    hostname: fireagg_db_insertion
    command: distributed core

  # db_benchmark:
  #   <<: *fireagg
  #   command: distributed symbols seesaw/synthetic

  btc_usd:
    <<: *fireagg
    command: distributed symbols BTC/USD BTC/USDT

  # eth_usd:
  #   <<: *fireagg
  #   command: distributed symbols ETH/USD ETH/USDT

  # crv_usd:
  #   <<: *fireagg
  #   command: distributed symbols CRV/USD CRV/USDT

  # zrx_usd:
  #   <<: *fireagg
  #   command: distributed symbols ZRX/USD ZRX/USDT

volumes:
  redisdata:
  pgdata:

networks:
  main:
  metrics:
    external: true
